= De couragéise klenge Schneiderfootnote:[Eventuell ass daper déi besser Iwwersetzung, et kennt mer allerdéngs vereelzt fir. {uvi}]
:uvi: Umierkung vum Iwwersetzer.
:fn-lout: footnote:[https://de.wikipedia.org/wiki/Lot_(Einheit)[Eng al Eenheet fir d’Mass (Gewiicht).] Jee no Regioun waren ee Lot 14 bis 18 Gramm. https://dico.uni.lu/?sigle=LWB&lemid=L01513[Bei eis 16,66 Gramm.] Dat ass ongeféier een Zoppeläffel voll. 4 Lout ≈ 67 g. {uvi}]
:fn-pond: footnote:[Pond ass och eng al Eenheet fir d'Mass. Ass nach geleefeg an entsprecht 500 Gramm. 1/4 Pond = 125 g. {uvi}]

Enges Summermoien souz e klenge Schneider op sengem Dësch bei der Fënster, hien hat gutt Laun a huet fläisseg gebitzt.
Dunn koum eng Bauerefra duerch d'Strooss a huet geruff: "Gudde Kompott ze verkafen! Gudde Kompott ze verkafen!"

Dee Klang huet dem Schneider gefall, hien huet säin zaarte Kapp aus dem Fënster gestach a geruff: "Kommt heihin, léif Fra, hei gitt Dir är Wuer lass."

D' Fra ass déi dräi Trape mat hirem schwéierem Kuerf bis bei de Schneider ropgaang an huet do missen all hier Deppe virun hie stellen.
Hien huet se sech all ugekuckt, an d'Luucht gehal, dru geroch an endlech gesot:
"Dëse Kompott schéngt mer gutt!
Gutt Fra, maacht mer véier Lout{fn-lout}.
An wann et ee Véirelspond{fn-pond} gëtt, dann ass et och an der Rei."

D'Fra huet em ginn, wat e gefrot hat.
Mee well se gehofft hat, kënne vill mam Schneider ze verdéngen, ass se veriergert a knoutereg fort gaang.

"Gott soll mer de Kompott seenen", huet de klenge Schneider geruff, "a soll mer Kraaft a Stäerkt ginn".
Dunn huet en d'Brot aus dem Schaf geholl, huet sech eng Schmier ofgeschnidden a Kompott drop geschmiert.
"Dat gëtt keng batter Schmier", sot en, "mee fir d'éischt maen ech de Gilet nach fäerdeg, ier ech se eessen."

Hien huet d'Brot nieft sech geluecht, huet weider gebitzt a viru Freed ëmmer méi grouss Stéch gemeet.
Wärenddeems huet de séisse Kompott sou gutt geroch, dat och déi vill Mécken un der Mauer d'Schmier bemierkt hunn.
Vum Geroch ugelackelt hunn si sech kéipweis drop gesat.

"Hej! Wien huet iech dann invitéiert?", sot de klenge Schneider an huet déi ongebiede Gäscht verjot.
Mee d'Mécke konnte kee Lëtzebuergesch an hunn sech net ofweise gelooss.
Et goufen der souguer ëmmer mei!
Do ass et dem Schneider duer gaang an a senger Roserei huet en d'Kichenduch geholl.
"Waart! Iech weisen ech et!" an huet ouni ze zecken drop gehae.
Wéi en d'Duch wech geholl a gezielt huet, du louchen do net manner wéi siwen dout Mécke virun him an hunn d'Bee wech gestreckt.

"Wat bass du ee Kärel!", huet e gesot an hien huet sech selwer bewonnert.
"Dat muss ech jiddereen aus der Staat gewuer ginn,"
Do huet sech de klenge Schneider ee Rimm gemeet an grouss Buschtawen drop brodéiert:

"Siwen op ee Streech!"

"Mee wat, Staad!" sot e weider. "Déi ganz Welt soll et gewuer ginn!"
An säin Häerz huet vu Freed gewackelt wéi e Lämmerchersschwänzchen.
De Schneider huet sech de Rimm ugedoen a wollt d'Welt entdecken, well en der Meenung war, datt säin Atelier ze kleng fir säi Courage wier.
Mee ier en sech op de Wee gemeet huet, huet en em d"Haus no nëtzleche Saache gesicht, déi hie mathuelen kéint .
Dat eenzegt wat e fonnt hat, war een ale Kéis, den en agepak hat.
Virun der Paart war him ee Villchen opgefall, deen sech am Gestraich verfaang hat, den huet e bei de Kéis an d'Täsch gestach.

Voller Courage huet en sech op de Wee gemeet, an well hien liicht an gescheckt war, ass en net mitt gin.
De Wee huet en op e Bierg gefouert, a wei en un der héchster Spëtzt ukomm ass, souz do e gewaltege Ris, de gemälleg em d'sech gekuckt huet.

De klenge Schneider ass voller Courage op en duergaang an huet en ugeschwat: "Moie Komper! Du sëtz hei a kucks an déi grouss Welt? Ech sinn op der Rees dohin a wëll mäi Gléck probéieren. Häss du Loscht matzegoen?"
De Ris huet de Schneider vun uewe rof gekuckt an huet gesot: "Du Lompekärel! Du bass sou miserabel!"
"Wann s de mengs!" huet de klenge Schneider geäntwert, huet sei Gilet opgeknäppt an huet dem Ris sei Rimm gewisen. "Hei kanns de liesen, wat ech fir een Dichtege sinn."

De Ris huet "Siwen op ee Streech!" gelies, huet gemengt, et wiere Mënsche gewiescht, déi de Schneider erschloen hätt, an huet dowéinst dee klenge Kärel liicht respektéiert.
Mee hie wollt en d'éischt nach testen, huet e Steen an d'Hand geholl an deen sou staark zesummegedréckt, datt Waasser rausgedrëpst ass.
"Maa mer dat mol no, ", sot de Ris, "wann s de staark bass."
"Wann et sos näischt ass!" sot de klenge Schneider. "Dat ass dach eng Spillerei."
En huet an d'Täsch gegraff, den ale Kéis rausgeholl an esou staark gedréckt, datt de Jus rausgelaf ass.
"Kuck mol!", sot en, "dat war nach e bësse besser, oder?"

De Ris wousst net, wat e soe sollt, a konnt net gleewen, wat de Männche gemeet hat.
Dofir huet de Ris e Stee geholl an sou héich an d'Luucht gehäit, datt een e mat bloussem A bal net mei konnt gesinn.
"Sou! Du Intebinnes, maa mer dat mol no."
"Gutt geworf", sot de Schneider, "mee de Steen ass dach rëm rofgefall. Ech wäert der ee werfen, dee guer net méi zeréckkënnt".
Huet dunn an d'Täsch gegraff, de Villche rausgeholl an deen an d'Loft gehäit.
De Villche war frou iwwer seng Fräiheet, ass an d'Luucht a fort geflunn an ass net méi zréckkomm.
"An, Komper? Wei gefält der dat Konschtstéck?" huet de Schneider gefrot.

"Werfe kanns de", sot de Ris, "mee lo wëll ech wësse, ob s de kapabel bass éierbar ze droen."
Hien huet dem Schneider eng deck Eech gewis, déi ëmgeha um Budem louch, a sot: "Wann s de staark genuch bass, dann hëllef mer dëse Bam aus dem Bësch rauszedroen."
"Gäre", huet de klenge Mann geäntwert, "huel du de Stamm op deng Schëller, an ech droen d'Äscht an d'Zweiger, well déi si jo am schwéiersten."

