= De couragéise klenge Schneiderfootnote:[Eventuell ass daper déi besser Iwwersetzung, et kennt mer allerdéngs vereelzt fir. {uvi}]
:uvi: Umierkung vum Iwwersetzer.
:fn-lout: footnote:[https://de.wikipedia.org/wiki/Lot_(Einheit)[Eng al Eenheet fir d’Mass (Gewiicht).] Jee no Regioun waren ee Lot 14 bis 18 Gramm. https://dico.uni.lu/?sigle=LWB&lemid=L01513[Bei eis 16,66 Gramm.] Dat ass ongeféier een Zoppeläffel voll. 4 Lout ≈ 67 g. {uvi}]
:fn-pond: footnote:[Pond ass och eng al Eenheet fir d'Mass. Ass nach geleefeg an entsprecht 500 Gramm. 1/4 Pond = 125 g. {uvi}]

Enges Summermoien souz e klenge Schneider op sengem Dësch bei der Fënster, hien hat gutt Laun a huet fläisseg gebitzt.
Dunn koum eng Bauerefra duerch d'Strooss a huet geruff: "Gudde Kompott ze verkafen! Gudde Kompott ze verkafen!"

Dee Klang huet dem Schneider gefall, hien huet säin zaarte Kapp aus dem Fënster gestach a geruff: "Kommt heihin, léif Fra, hei gitt Dir är Wuer lass."

D' Fra ass déi dräi Trape mat hirem schwéierem Kuerf bis bei de Schneider ropgaang an huet do missen all hier Deppe virun hie stellen.
Hien huet se sech all ugekuckt, an d'Luucht gehal, dru geroch an endlech gesot:
"Dëse Kompott schéngt mer gutt!
Gutt Fra, maacht mer véier Lout{fn-lout}.
An wann et ee Véirelspond{fn-pond} gëtt, dann ass et och an der Rei."

D'Fra huet em ginn, wat e gefrot hat.
Mee well se gehofft hat, kënne vill mam Schneider ze verdéngen, ass se veriergert a knoutereg fort gaang.

"Gott soll mer de Kompott seenen", huet de klenge Schneider geruff, "a soll mer Kraaft a Stäerkt ginn".
Dunn huet en d'Brot aus dem Schaf geholl, huet sech eng Schmier ofgeschnidden a Kompott drop geschmiert.
"Dat gëtt keng batter Schmier", sot en, "mee fir d'éischt maen ech de Gilet nach fäerdeg, ier ech se eessen."

Hien huet d'Brot nieft sech geluecht, huet weider gebitzt a viru Freed ëmmer méi grouss Stéch gemeet.
Wärenddeems huet de séisse Kompott sou gutt geroch, dat och déi vill Mécken un der Mauer d'Schmier bemierkt hunn.
Vum Geroch ugelackelt hunn si sech kéipweis drop gesat.

"Hej! Wien huet iech dann invitéiert?", sot de klenge Schneider an huet déi ongebiede Gäscht verjot.
Mee d'Mécke konnte kee Lëtzebuergesch an hunn sech net ofweise gelooss.
Et goufen der souguer ëmmer mei!
Do ass et dem Schneider duer gaang an a senger Roserei huet en d'Kichenduch geholl.
"Waart! Iech weisen ech et!" an huet ouni ze zecken drop gehae.
Wéi en d'Duch wech geholl a gezielt huet, du louchen do net manner wéi siwen dout Mécke virun him an hunn d'Bee wech gestreckt.

"Wat bass du ee Kärel!", huet e gesot an hien huet sech selwer bewonnert.
"Dat muss ech jiddereen aus der Staat gewuer ginn,"
Do huet sech de klenge Schneider ee Rimm gemeet an grouss Buschtawen drop brodéiert:

"Siwen op ee Streech!"

"Mee wat, Staad!" sot e weider. "Déi ganz Welt soll et gewuer ginn!"
An säin Häerz huet vu Freed gewackelt wéi e Lämmerchersschwänzchen.
De Schneider huet sech de Rimm ugedoen a wollt d'Welt entdecken, well en der Meenung war, datt säin Atelier ze kleng fir säi Courage wier.
Mee ier en sech op de Wee gemeet huet, huet en em d"Haus no nëtzleche Saache gesicht, déi hie mathuelen kéint .
Dat eenzegt wat e fonnt hat, war een ale Kéis, den en agepak hat.
Virun der Paart war him ee Villchen opgefall, deen sech am Gestraich verfaang hat, den huet e bei de Kéis an d'Täsch gestach.

Voller Courage huet en sech op de Wee gemeet, an well hien liicht an gescheckt war, ass en net mitt gin.
De Wee huet en op e Bierg gefouert, a wei en un der héchster Spëtzt ukomm ass, souz do e gewaltege Ris, de gemälleg em d'sech gekuckt huet.

De klenge Schneider ass voller Courage op en duergaang an huet en ugeschwat: "Moie Komper! Du sëtz hei a kucks an déi grouss Welt? Ech sinn op der Rees dohin a wëll mäi Gléck probéieren. Häss du Loscht matzegoen?"
De Ris huet de Schneider vun uewe rof gekuckt an huet gesot: "Du Lompekärel! Du bass sou miserabel!"
"Wann s de mengs!" huet de klenge Schneider geäntwert, huet sei Gilet opgeknäppt an huet dem Ris sei Rimm gewisen. "Hei kanns de liesen, wat ech fir een Dichtege sinn."

De Ris huet "Siwen op ee Streech!" gelies, huet gemengt, et wiere Mënsche gewiescht, déi de Schneider erschloen hätt, an huet dowéinst dee klenge Kärel liicht respektéiert.
Mee hie wollt en d'éischt nach testen, huet e Steen an d'Hand geholl an deen sou staark zesummegedréckt, datt Waasser rausgedrëpst ass.
"Maa mer dat mol no, ", sot de Ris, "wann s de staark bass."
"Wann et sos näischt ass!" sot de klenge Schneider. "Dat ass dach eng Spillerei."
En huet an d'Täsch gegraff, den ale Kéis rausgeholl an esou staark gedréckt, datt de Jus rausgelaf ass.
"Kuck mol!", sot en, "dat war nach e bësse besser, oder?"

De Ris wousst net, wat e soe sollt, a konnt net gleewen, wat de Männche gemeet hat.
Dofir huet de Ris e Stee geholl an sou héich an d'Luucht gehäit, datt een e mat bloussem A bal net mei konnt gesinn.
"Sou! Du Intebinnes, maa mer dat mol no."
"Gutt geworf", sot de Schneider, "mee de Steen ass dach rëm rofgefall. Ech wäert der ee werfen, dee guer net méi zeréckkënnt".
Huet dunn an d'Täsch gegraff, de Villche rausgeholl an deen an d'Loft gehäit.
De Villche war frou iwwer seng Fräiheet, ass an d'Luucht a fort geflunn an ass net méi zréckkomm.
"An, Komper? Wei gefält der dat Konschtstéck?" huet de Schneider gefrot.

"Werfe kanns de", sot de Ris, "mee lo wëll ech wësse, ob s de kapabel bass éierbar ze droen."
Hien huet dem Schneider eng deck Eech gewis, déi ëmgeha um Budem louch, a sot: "Wann s de staark genuch bass, dann hëllef mer dëse Bam aus dem Bësch rauszedroen."
"Gäre", huet de klenge Mann geäntwert, "huel du de Stamm op deng Schëller, an ech droen d'Äscht an d'Zweiger, well déi si jo am schwéiersten."

De Ris huet de Stamm op seng Schëller geholl, mee de Schneider huet sech op en Äscht gesat.
De Ris, den net mei hannert sech kucke konnt, huet dunn de ganze Bam, mam klenge Schneider drop, fortgedroe.
De Schneider souz hannendrop, war lëschteg a gutt drop an huet dat Liddche "Es ritten drei Schneider zum Tore hinaus" gepaff, sou wei wann d'Bamdroen e Kannerspill wier.
Nodeems de Ris schonn ee Stéck vum Wee de schwéire Bam gedroen hat, konnt en net mei an huet geruff: "Lauschter mol, ech muss de Bam fale loossen."
De Schneider ass séier rofgesprong an huet de Bam sou ugepak wéi wann hien e gedro hätt, a huet zum Ris gesot: "Du bass sou grouss a kanns net mol dee Bam hei droen."

Si sinn zesumme weidergaang, bis se bei ee Kiischtebam komm sinn.
De Ris huet d'Kroun vum Bam, wou schonn zeideg Friichten dru waren, erofgezunn an dem Schneider an d'Hand gedréckt, fir dat e kéint Kiischten eesen.
Mee de Schneider war vill ze schwaach, fir de Bam selwer ze halen, a nodeems de Ris lassgelooss huet, ass de Bam rëm an d'Luucht geschoss.
An de Schneider mat.
Ouni sech wéizedoen ass de Schneider rem rofgefall an dunn huet de Ris gesot:
"Wat ass da lass? Hues du net genuch Kraaft, fir déi aarmséileg Rutt ënnen ze halen?"
"Kraaft hunn ech genuch", huet de klenge Schneider geäntwert, "mengs de, dat wier eng Affär, fir een deen der siwen op ee Streech getraff hätt?
Ech sinn iwwert de Bam gesprong, well d'Jeeër do hannen an den Hecke schéissen
Sprang och, wann s de et kanns."
De Ris huet et och probéiert, mee ass net iwwer de Bam komm, well en an den Äscht hänke bliwwen ass, sou dat de klenge Schneider och dat besser gemeeschtert hat wéi de Ris.

Do huet de Ris gesoot: "Wanns de sou dichteg bass, da komm mat bei eis an d'Höl an schloof bei eis."
De klenge Schneider war averstan an ass matgaang.
Wéi se an d'Höl koumen, souzen nach aner Risen em d'Feier, a jiddwereen hat ee gebrode Schof am Grapp an huet et gees.
De Schneider huet sech ëm sech gekuckt a geduecht, hei ass et awer vill méi grouss wéi a mengem Atelier.
De Ris huet em e Bett gewis an gesot, dat en sech soll dra leeën a ausschlofen.
Well dem klenge Schneider war d'Bett ze grouss, an en huet sech net drageluecht, mee huet sech an eng Eck gekuschelt.
Ëm Mëtternuecht war de Ris der Meenung, dat de Schneider ging déif schlofen, dofir ass en opgestan, huet eng Eisestaang geholl, an huet d'Bett mat engem Schlag entzwee geha, an huet geduecht hien hätt den Heesprénger futti gemeet.
Moies fréi sinn d'Risen an de Bësch gaang an haten de klenge Schneider scho vergees, bis en hinne lëschteg an ouni Angscht entgéintkomm ass.
Do ass hinnen d'Häerz an d'Box gerutscht, well se duechten hie ging se all dout schloen, an si si séier fortgelaf.

De Schneider ass weider gaang, ëmmer senger spatzer Nues no.
Nodeems e laang gewandert war, ass en an den Haff vun engem kinnekleche Palais komm, a well e midd war, huet en sech do an d'Gras geluecht a geschlof.
Iwwerdeems en do louch, koumen d'Leit an hunn e vun all Säit gekuckt a gelies wat op sengem Rimm stoung:
"Siwen op ee Streech!"
"O", soten se, "wat mécht dee grousse Krichsheld dann hei matten am Fridden? Dat muss jo ee mächtegen Här sinn."
Se si bei hire Kinnek gaang an hunn dat gemellt a gemengt, wann et sollt Krich ginn, da wier dat ee wichtegen an nëtzleche Mann, deen een ënner kengen Ëmstänn dierft fortgoe loossen.
Dem Kinnek huet dee Rot gefall, an hien huet ee vu senge Conseiller bei de klenge Schneider geschéckt.
Dee sollt waarde bis e waakreg gëtt an him dann de Krichsdéngscht proposéieren.
De Conseiller ass beim Schléifer stoe bliff, an huet gewaart bis deen sech gestreckt an d'Aen opgemaach hat, fir dunn seng Propos ze maen.
"Genau dofir sinn ech heihikomm", huet de klenge Schneider geäntwert, "ech si prett an dem Kinnek zu Déngschten."
Dofir ass en éierevoll empfaang ginn an huet dierfen ee spezielle Quartéier bezeien.

D'Zaldoten hunn dem klenge Schneider seng Spiicht gegleeft an hunn sech gewënscht, dat en dausend Meile wäit fort wier.
"Wat solle mer da maan, wa mer eis mat em streiden?", hunn si sech gefrot.
"Wann e schléit, da fale jo mat all Streech siwe vun eis. Do hu mer hu jo keng Chance."
Si hunn eng Entscheedung getraff, sinn all zesumme bei de Kinnek gaang an hunn em hir Entloossung gebueden.
"Mir sinn net dofir gemaach", hunn si gesot, "et nieft engem Mann auszehalen, deen der siwen op ee Streech schléit."

De Kinnek war traureg, fir séi Wëllen duerchzesetzen, ging en all seng Dénger verléiren.
Dofir huet en sech gewënscht, dat en de Schneider ni gesinn hätt an hie wier e rëm gär lass.
Mee en huet sech net getraut, hien ze entloossen, well en Angscht hat, dat de Schneider dann hien a séi ganzt Vollek ging doutschloen an sech da selwer op de kinneklechen Troun setzt.
En huet laang getiermt, an endlech hat en eng Iddi.
Hien huet rëm e Conseiller bei de Schneider geschéckt an dee sollt em soen, well en sou grousse Krichsheld wier, ging de Kinnek him eng speziell Propos maan.
An engem Bësch hunn zwee Rise gehaust, déi mat Iwwerfäll, Mord a Dierfer verbrenne grouss Schied maan, an et konnt kee bei si goen, ouni a Liewensgefor ze geroden.
Wann en déi zwee Rise ging iwwerwannen an dout maan, dann dierft en dem Kinnek seng eenzeg Duechter bestueden a sollt dat halleft Kinnekräich als Dottfootnote:[Mitgift, original Ehesteuer {uvi}] kréien.
Ausserdeem sollten nach honnert Reider mat em goe, fir en ze ënnerstëtzen.
Dat ass genau dat richteg fir ee Mann, wéis du et bass, huet de Schneider sech geduecht, an eng schéi Kinneksduechter an een halleft Kinnekräich kritt een och net all Daach proposéiert.
"O jo", huet e geäntwert, "déi Rise wäert ech bännegen an déi honnert Reider wär ech net brauchen; ween der siwen op ee Streech trefft, brauch der zwee net ze fäerten."

Der klenge Schneider huet sech op de Wee gemät, an déi honnert Reider him hannendrun.
Wei se bei de Bësch komm sinn, huet en zu senge Begleeder gesot:
"Bleift dir nëmmen hei, ech wäert schonn aleng mat de Risen eens ginn."
Dunn ass en an de Bësch ra gesprong an huet lenks a riets gekuckt.
No enger Zäitchen huet en déi zwee Rise gesinn:
Si louchen ënnert engem Bam, hu geschlof an sou staark geschnaarcht, dat d'Äscht sech rop a rof gebéit hunn.
De klenge Schneider huet sech direkt un d'Aarbescht gemeet, sech Täschen mat Steng gefellt an ass op de Bam geklom.
An der Mëtt vum Bam, ass en op een Aascht gerutscht, bis e genau iwwert de Schléifer souz, an huet dunn dem enge Ris ee Steen nom aner op d'Broscht fale gelooss.
De Ris huet laang näischt gemierkt, wéi en dun awer wackreg gin ass, huet e sei Kolleg gestouss an soot: "Firwa schléis du mech?"







