= De couragéise klenge Schneiderfootnote:[Eventuell ass daper déi besser Iwwersetzung, et kennt mer allerdéngs vereelzt fir. {uvi}]
:uvi: Umierkung vum Iwwersetzer.
:fn-lout: footnote:[https://de.wikipedia.org/wiki/Lot_(Einheit)[Eng al Eenheet fir d’Mass (Gewiicht).] Jee no Regioun waren ee Lot 14 bis 18 Gramm. https://dico.uni.lu/?sigle=LWB&lemid=L01513[Bei eis 16,66 Gramm.] Dat ass ongeféier een Zoppeläffel voll. 4 Lout ≈ 67 g. {uvi}]
:fn-pond: footnote:[Pond ass och eng al Eenheet fir d'Mass. Ass nach geleefeg an entsprecht 500 Gramm. 1/4 Pond = 125 g. {uvi}]

Enges Summermoien souz e klenge Schneider op sengem Dësch bei der Fënster, en hat gutt Laun a huet fläisseg gebitzt.
Dunn koum eng Bauerefra duerch d'Strooss a huet geruff: "Gudde Kompott ze verkafen! Gudde Kompott ze verkafen!" +
Dee Klang huet dem Schneider gefall, hien huet säin zaarte Kapp aus dem Fënster gestach a geruff: "Kommt heihin, léif Fra, hei gitt Dir är Wuer lass." +
D' Fra ass déi dräi Trape mat hirem schwéierem Kuerf bis bei de Schneider ropgaang an huet do missen all hier Deppe virun hie stellen.
Hien huet se sech all ugekuckt, an d'Luucht gehal, dru geroch an endlech gesot:
"Dëse Kompott schéngt mer gutt!
Gutt Fra, maacht mer véier Lout{fn-lout}.
An wann et ee Véirelspond{fn-pond} gëtt, dann ass et och an der Rei." +
D'Fra huet em ginn, wat e gefrot hat.
Mee well se gehofft hat, kënne vill mam Schneider ze verdéngen, ass se veriergert a knoutereg fort gaang.

"Gott soll mer de Kompott seenen", huet de klenge Schneider geruff, "a soll mer Kraaft a Stäerkt ginn".
Dunn huet en d'Brot aus dem Schaf geholl, huet sech eng Schmier ofgeschnidden a Kompott drop geschmiert.
"Dat gëtt keng batter Schmier", sot en, "mee fir d'éischt maen ech de Gilet nach fäerdeg, ier ech se eessen." +
En huet d'Brot nieft sech geluecht, huet weider gebitzt a viru Freed ëmmer méi grouss Stéch gemeet.
Wärenddeems huet de séisse Kompott sou gutt geroch, dat och déi vill Mécken un der Mauer d'Schmier bemierkt hunn.
Vum Geroch ugelackelt hunn si sech kéipweis drop gesat. +
"Hej! Wien huet iech dann invitéiert?", sot de klenge Schneider an huet déi ongebiede Gäscht verjot.
Mee d'Mécke konnte kee Lëtzebuergesch an hunn sech net ofweise gelooss.
Et goufen der souguer ëmmer mei!
Do ass et dem Schneider duer gaang an a senger Roserei huet en d'Kichenduch geholl. +
"Waart! Iech weisen ech et!" an huet ouni ze zecken drop gehae. +
Wéi en d'Duch wech geholl a gezielt huet, du louchen do net manner wéi siwen dout Mécke virun him an hunn d'Bee wech gestreckt. +
"Wat bass du ee Kärel!", huet e gesot an hien huet sech selwer bewonnert.
"Dat muss ech jiddereen aus der Staat gewuer ginn." +
Do huet sech de klenge Schneider ee Rimm gemeet an grouss Buschtawen drop brodéiert:

"Siwen op ee Streech!"

"Mee wat, Staad!" sot e weider. "Déi ganz Welt soll et gewuer ginn!"
An säin Häerz huet vu Freed gewackelt wéi e Lämmerchersschwänzchen.
De Schneider huet sech de Rimm ugedoen a wollt d'Welt entdecken, well en der Meenung war, datt säin Atelier ze kleng fir säi Courage wier.
Mee ier en sech op de Wee gemeet huet, huet en em d"Haus no nëtzleche Saache gesicht, déi hie mathuelen kéint .
Dat eenzegt wat e fonnt hat, war een ale Kéis, den en agepak hat.
Virun der Paart war him ee Villchen opgefall, deen sech am Gestraich verfaang hat, den huet e bei de Kéis an d'Täsch gestach.

Voller Courage huet en sech op de Wee gemeet, an well hien liicht an gescheckt war, ass en net mitt gin.
De Wee huet en op e Bierg gefouert, a wei en un der héchster Spëtzt ukomm ass, souz do e gewaltege Ris, de gemälleg em d'sech gekuckt huet.

De klenge Schneider ass voller Courage op en duergaang an huet en ugeschwat: "Moie Komper! Du sëtz hei a kucks an déi grouss Welt? Ech sinn op der Rees dohin a wëll mäi Gléck probéieren. Häss du Loscht matzegoen?"
De Ris huet de Schneider vun uewe rof gekuckt an huet gesot: "Du Lompekärel! Du bass sou miserabel!"
"Wann s de mengs!" huet de klenge Schneider geäntwert, huet sei Gilet opgeknäppt an huet dem Ris sei Rimm gewisen. "Hei kanns de liesen, wat ech fir een Dichtege sinn."

De Ris huet "Siwen op ee Streech!" gelies, huet gemengt, et wiere Mënsche gewiescht, déi de Schneider erschloen hätt, an huet dowéinst dee klenge Kärel liicht respektéiert.
Mee hie wollt en d'éischt nach testen, huet e Steen an d'Hand geholl an deen sou staark zesummegedréckt, datt Waasser rausgedrëpst ass.
"Maa mer dat mol no, ", sot de Ris, "wann s de staark bass."
"Wann et sos näischt ass!" sot de klenge Schneider. "Dat ass dach eng Spillerei."
En huet an d'Täsch gegraff, den ale Kéis rausgeholl an esou staark gedréckt, datt de Jus rausgelaf ass.
"Kuck mol!", sot en, "dat war nach e bësse besser, oder?"

De Ris wousst net, wat e soe sollt, a konnt net gleewen, wat de Männche gemeet hat.
Dofir huet de Ris e Stee geholl an sou héich an d'Luucht gehäit, datt een e mat bloussem A bal net mei konnt gesinn.
"Sou! Du Intebinnes, maa mer dat mol no."
"Gutt geworf", sot de Schneider, "mee de Steen ass dach rëm rofgefall. Ech wäert der ee werfen, dee guer net méi zeréckkënnt".
Huet dunn an d'Täsch gegraff, de Villche rausgeholl an deen an d'Loft gehäit.
De Villche war frou iwwer seng Fräiheet, ass an d'Luucht a fort geflunn an ass net méi zréckkomm.
"An, Komper? Wei gefält der dat Konschtstéck?" huet de Schneider gefrot.

"Werfe kanns de", sot de Ris, "mee lo wëll ech wësse, ob s de kapabel bass éierbar ze droen."
Hien huet dem Schneider eng deck Eech gewis, déi ëmgeha um Budem louch, a sot: "Wann s de staark genuch bass, dann hëllef mer dëse Bam aus dem Bësch rauszedroen."
"Gäre", huet de klenge Mann geäntwert, "huel du de Stamm op deng Schëller, an ech droen d'Äscht an d'Zweiger, well déi si jo am schwéiersten."

De Ris huet de Stamm op seng Schëller geholl, mee de Schneider huet sech op en Äscht gesat.
De Ris, den net mei hannert sech kucke konnt, huet dunn de ganze Bam, mam klenge Schneider drop, fortgedroe.
De Schneider souz hannendrop, war lëschteg a gutt drop an huet dat Liddche "Es ritten drei Schneider zum Tore hinaus" gepaff, sou wei wann d'Bamdroen e Kannerspill wier.
Nodeems de Ris schonn ee Stéck vum Wee de schwéire Bam gedroen hat, konnt en net mei an huet geruff: "Lauschter mol, ech muss de Bam fale loossen."
De Schneider ass séier rofgesprong an huet de Bam sou ugepak wéi wann hien e gedro hätt, a huet zum Ris gesot: "Du bass sou grouss a kanns net mol dee Bam hei droen."

Si sinn zesumme weidergaang, bis se bei ee Kiischtebam komm sinn.
De Ris huet d'Kroun vum Bam, wou schonn zeideg Friichten dru waren, erofgezunn an dem Schneider an d'Hand gedréckt, fir dat e kéint Kiischten eesen.
Mee de Schneider war vill ze schwaach, fir de Bam selwer ze halen, a nodeems de Ris lassgelooss huet, ass de Bam rëm an d'Luucht geschoss.
An de Schneider mat.
Ouni sech wéizedoen ass de Schneider rem rofgefall an dunn huet de Ris gesot:
"Wat ass da lass? Hues du net genuch Kraaft, fir déi aarmséileg Rutt ënnen ze halen?"
"Kraaft hunn ech genuch", huet de klenge Schneider geäntwert, "mengs de, dat wier eng Affär, fir een deen der siwen op ee Streech getraff hätt?
Ech sinn iwwert de Bam gesprong, well d'Jeeër do hannen an den Hecke schéissen
Sprang och, wann s de et kanns."
De Ris huet et och probéiert, mee ass net iwwer de Bam komm, well en an den Äscht hänke bliwwen ass, sou dat de klenge Schneider och dat besser gemeeschtert hat wéi de Ris.

Do huet de Ris gesoot: "Wanns de sou dichteg bass, da komm mat bei eis an d'Höl an schloof bei eis."
De klenge Schneider war averstan an ass matgaang.
Wéi se an d'Höl koumen, souzen nach aner Risen em d'Feier, a jiddwereen hat ee gebrode Schof am Grapp an huet et gees.
De Schneider huet sech ëm sech gekuckt a geduecht, hei ass et awer vill méi grouss wéi a mengem Atelier.
De Ris huet em e Bett gewis an gesot, dat en sech soll dra leeën a ausschlofen.
Well dem klenge Schneider war d'Bett ze grouss, an en huet sech net drageluecht, mee huet sech an eng Eck gekuschelt.
Ëm Mëtternuecht war de Ris der Meenung, dat de Schneider ging déif schlofen, dofir ass en opgestan, huet eng Eisestaang geholl, an huet d'Bett mat engem Schlag entzwee geha, an huet geduecht hien hätt den Heesprénger futti gemeet.
Moies fréi sinn d'Risen an de Bësch gaang an haten de klenge Schneider scho vergees, bis en hinne lëschteg an ouni Angscht entgéintkomm ass.
Do ass hinnen d'Häerz an d'Box gerutscht, well se duechten hie ging se all dout schloen, an si si séier fortgelaf.

De Schneider ass weider gaang, ëmmer senger spatzer Nues no.
Nodeems e laang gewandert war, ass en an den Haff vun engem kinnekleche Palais komm, a well e midd war, huet en sech do an d'Gras geluecht a geschlof.
Iwwerdeems en do louch, koumen d'Leit an hunn e vun all Säit gekuckt a gelies wat op sengem Rimm stoung:
"Siwen op ee Streech!"
"O", soten se, "wat mécht dee grousse Krichsheld dann hei matten am Fridden? Dat muss jo ee mächtegen Här sinn."
Se si bei hire Kinnek gaang an hunn dat gemellt a gemengt, wann et sollt Krich ginn, da wier dat ee wichtegen an nëtzleche Mann, deen een ënner kengen Ëmstänn dierft fortgoe loossen.
Dem Kinnek huet dee Rot gefall, an hien huet ee vu senge Conseiller bei de klenge Schneider geschéckt.
Dee sollt waarde bis e waakreg gëtt an him dann de Krichsdéngscht proposéieren.
De Conseiller ass beim Schléifer stoe bliff, an huet gewaart bis deen sech gestreckt an d'Aen opgemaach hat, fir dunn seng Propos ze maen.
"Genau dofir sinn ech heihikomm", huet de klenge Schneider geäntwert, "ech si prett an dem Kinnek zu Déngschten."
Dofir ass en éierevoll empfaang ginn an huet dierfen ee spezielle Quartéier bezeien.

D'Zaldoten hunn dem klenge Schneider seng Spiicht gegleeft an hunn sech gewënscht, dat en dausend Meile wäit fort wier.
"Wat solle mer da maan, wa mer eis mat em streiden?", hunn si sech gefrot.
"Wann e schléit, da fale jo mat all Streech siwe vun eis. Do hu mer hu jo keng Chance."
Si hunn eng Entscheedung getraff, sinn all zesumme bei de Kinnek gaang an hunn em hir Entloossung gebueden.
"Mir sinn net dofir gemaach", hunn si gesot, "et nieft engem Mann auszehalen, deen der siwen op ee Streech schléit."

De Kinnek war traureg, fir séi Wëllen duerchzesetzen, ging en all seng Dénger verléiren.
Dofir huet en sech gewënscht, dat en de Schneider ni gesinn hätt an hie wier e rëm gär lass.
Mee en huet sech net getraut, hien ze entloossen, well en Angscht hat, dat de Schneider dann hien a séi ganzt Vollek ging doutschloen an sech da selwer op de kinneklechen Troun setzt.
En huet laang getiermt, an endlech hat en eng Iddi.
Hien huet rëm e Conseiller bei de Schneider geschéckt an dee sollt em soen, well en sou grousse Krichsheld wier, ging de Kinnek him eng speziell Propos maan.
An engem Bësch hunn zwee Rise gehaust, déi mat Iwwerfäll, Mord a Dierfer verbrenne grouss Schied maan, an et konnt kee bei si goen, ouni a Liewensgefor ze geroden.
Wann en déi zwee Rise ging iwwerwannen an dout maan, dann dierft en dem Kinnek seng eenzeg Duechter bestueden a sollt dat halleft Kinnekräich als Dottfootnote:[Mitgift, original Ehesteuer {uvi}] kréien.
Ausserdeem sollten nach honnert Reider mat em goe, fir en ze ënnerstëtzen.
Dat ass genau dat richteg fir ee Mann, wéis du et bass, huet de Schneider sech geduecht, an eng schéi Kinneksduechter an een halleft Kinnekräich kritt een och net all Daach proposéiert.
"O jo", huet e geäntwert, "déi Rise wäert ech bännegen an déi honnert Reider wär ech net brauchen; ween der siwen op ee Streech trefft, brauch der zwee net ze fäerten."

Der klenge Schneider huet sech op de Wee gemät, an déi honnert Reider him hannendrun.
Wei se bei de Bësch komm sinn, huet en zu senge Begleeder gesot:
"Bleift dir nëmmen hei, ech wäert schonn aleng mat de Risen eens ginn."
Dunn ass en an de Bësch ra gesprong an huet lenks a riets gekuckt.
No enger Zäitchen huet en déi zwee Rise gesinn:
Si louchen ënnert engem Bam, hu geschlof an sou staark geschnaarcht, dat d'Äscht sech rop a rof gebéit hunn.
De klenge Schneider huet sech direkt un d'Aarbescht gemeet, sech Täschen mat Steng gefellt an ass op de Bam geklom.
An der Mëtt vum Bam, ass en op een Aascht gerutscht, bis e genau iwwert de Schléifer souz, an huet dunn dem enge Ris ee Steen nom aner op d'Broscht fale gelooss.
De Ris huet laang näischt gemierkt, wéi en dun awer wackreg gin ass, huet e sei Kolleg gestouss an soot: "Firwa schléis du mech?" +
"Du dreems", sot deen aneren, "ech schloen dech net." +
Si haaten sech rem geluecht an weider geschlof, du huet de Schneider een Steen op den zweeten Ris geheit. +
"Wat soll dat?" huet den aner geruff.
"Firwa werfs de op mech?" +
"Ech werfen net op dech.", huet den éischte gegrommelt. +
Si hu sech eng Zäit laang gestridden, mee well se sou midd waren, hun se opgehaal, an d'An si hinne rëm zougefall.
De klenge Schneider huet séi Spill rëm vu vir ugefaang, huet den déckste Stee geholl an en dem éischte Ris sou fest e konnt op d'Broscht geheit. +
"Dat ass uerg!" huet e Kreesch gedoe, ass wéi vum Lämmes gebass opgesprong an huet sei Kolleeg widder de Bam gestouss, dat dee geziddert huet.
Deen aner huet sech zerguttst revanchéiert, a si hunn sou eng Roserei u sech krut, dat se Beem rausgerappt, an sou laang openee geschlo hunn, bis ze zur selwechter Zäit dout ëmgefall sinn.
Réischt dunn ass de klenge Schneider rëm rof gesprong. +
"Waat haat ech eng Chance", soot en, "dat se de Bam, op deem ech souz, net rausgerappt hin.
Sos hätt ech wéi ee Kaweechelche missen an een anere Bam sprange:
Mee ech ka mech séier duerch d'Bascht maan!"
Dunn huet e sei Schwäert geholl an huet jiddferengem puer mol an d'Broscht gestach, ass rëm zréck bei d'Reider gaang an huet gesot:
"Meng Aarbecht ass gedo, déi zwee sinn dout; mee et ass haart hiergaang, an hirer Nout hunn se d'Beem rausgerappt an sech gewiert, mee dat huet hinnen net géint ee gehollef, den der siwen op ee Streech schléit." +
"Sidd der net verwonnt?" hunn d'Reider gefrot. +
"Mir geet et gutt", huet de Schneider geäntwert, "keen Hoer hunn se mer gekrëmmt." +
D'Reider konnten em net gleewen an si an de Bësch geridden: Do hunn se d'Rise fonnt, déi an hirem eegene Blutt louchen an ëm d'se stoung kee Bam méi.

De Schneider wollt dunn déi Belounung, déi de Kinnek him versprach hat.
Mee dem huet et leet gedo, dat en dat Verspriech ginn hat, an huet sech iwwerluecht, wéi en den Held ging lass ginn. +
"Iers de meng Duechter an dat halleft Räich kriss", huet dem Kinnek him erkläert, "Muss du mer nach een Heldendéngscht erweise. Am Bescht gëtt een Einhorn, duerch dat vill Schued entsteet. Du muss et fir mech fänken." +
"Een Einhorn fäerten ech jo nach manner wéi zwee Rise; siwen op ee Streech, ass wat ech gutt kann."

En huet sech ee Stréck an eng Aaxt geholl, ass domat an de Bësch gaang, an huet senge Reider rëm gesot, dat se virum Bësch waarde sollen.
En huet net misse laang sichen, du koum d'Einhorn, ass op de Schneider duer gesprong, a wollt en opspiissen. +
"Maa lues, maa lues", sot en, "sou séier geet dat net." +
En ass stoen bliff an huet gewaart, bis d'Déier ganz noh bei em war, dunn ass en flénk hannert de Bam gesprong.
D'Einhorn ass mat senger ganzer Kraaft an de Bam gerannt an huet säin Har so fest an de Bam gespiisst, dat et net genuch Kraaft hat, fir e rauszezéien. +
"Lo hunn ech de Villche gefaang", sot de Schneider, ass hannert dem Bam raus komm, huet dem Einhorn de Stréck em de Hals geluecht, huet du mat der Aaxt d'Har aus dem Bam geschloe, a wei e fäerdeg war, ass e mam Déier bei de Kinnek gaang.

De Kinnek wollt em de versprachene Loun nach ëmmer net ginn an huet em nach eng drëtt Aufgab ginn.
De Schneider sollt em virun der Hochzäit nach ee Wëllschwäi fänken, dat am Bësch grouss Schied gemeet hat.
An d'Jeeër sollten dem Schneider hëllefen. +
"Gären", sot de Schneider, "dat ass ee Kannerspill."

D'Jeeër huet en net mat an de Bësch geholl, an domat waren se och zefridden, well d'Wëllschwäin hat se scho puer mol sou empfaang, dat se kéng Loscht haten, et ze joen.
Wéi d'Schwäin de Schneider gesinn huet, ass et op en duergelaf, krut Schaum virun d'Schnëss an huet d'Zeen gegrätscht, a wollt en op de Buedem werfen.
De Schneider ass an eng Kapell geflücht, déi nobäi war, an ass mat engem Saz rëm uewen zur Fënster raus.
D'Schwäi war em nogelaf, mee hien ass dobausse rëm virun d'Kapell gelaf an huet d'Dier hannert dem Schwäin zougeschlo.
Do war daat rosend Déier gefaang, well et war vill ze schwéier an
plomp fir zur Fënster kenne rauszesprangen.
De klenge Schneider huet d'Jeeër geruff, fir datt se dat gefaangent Déier selwer gesinn.
Den Held ass rëm zréck bei de Kinnek gaang, de lo, op e wollt oder net, säi Versprieche misst halen, an en huet em seng Duechter an dat halleft Kinnekräich ginn.
Hätt de Kinnek gewosst, dat keen Krichsheld, mee e klenge Schneider virun him stoung, da wier em d'Häerz nach méi schwéier gin.
D'Hochzäit gouf mat grousser Pruecht a klenger Freed gefeiert an aus engem Schneider gouf e Kinnek.

No enger Zäit huet déi jonk Kinnigin nuets hire Mann héieren am Schlof soen: "Borscht, maa er de Gilet a fleck mer d'Box, oder et ginn der mam Zollstaf." +
Doduerch huet hatt gemierkt, a wéi enger Gaass de jonken Här gebuer gouf, an huet hirem Papp de Moien drop hiert Leed geklot a wollt, dat en hatt vun dem Mann befreit, dee jo näischt anescht wéi ee Schneider war.
De Kinnek huet hat getréischt a sot: "Looss Hënt deng Kummerdier op, meng Dénger wäerten dobausse stoen, a wann e schléift, kommen se ran, fesselen en a droen en op ee Schëff, dat en an déi wäit Welt féiert." +
D'Fra war domat zefridden, mee dem Kinnek säi Squire, deen alles héieren hat, konnt de Schneider gutt leiden an huet em de ganze Plang verrot. +
"Dat wäert ech ënnerbannen.", sot de klenge Schneider.
Owes huet en sech wéi ëmmer nieft seng Fra an d'Bett geluecht.
Wei hatt gemengt hat, datt e géing schlofen, ass hat opgestan, huet Dier opgemeet an huet sech rëm an d'Bett geluecht.
De klenge Schneider, den nëmmen sou gemeet huet, wéi wann e géing schlofen, huet mat enger heller Stemm geruff:
"Borscht, maa er de Gilet a fleck mer d'Box, oder et ginn der mam Zollstaf!
Ech hunn der siwen op ee Streech getraff, zwee Risen erschlo, een Einhorn an ee Wëllschwäi gefaang a lo soll ech déi fäerten, déi viru menger Kummer stinn!" +
Wéi de Schneider dat sot, kruten se et mat der Angscht ze dinn, an se si fortgelaf, wéi wann déi wëll Jeeër hannert e wier, duerno huet sech kee méi getraut sech mam Schneider unzeleeën.
Also ass de klenge Schneider sengerliewe laang Kinnek bliff.












